"""
MarketOS — SendGrid Email Delivery
PRD §7: SendGrid primary + AWS SES fallback.

Replaces the SMTP implementation. SendGrid provides:
- Webhook events (opens, clicks, bounces → contact.events Kafka topic)
- Suppression list management
- DKIM/SPF authentication
- Real-time delivery tracking

Demo mode: falls back to SMTP if SENDGRID_API_KEY not set.
Production: set SENDGRID_API_KEY in .env.
"""

from __future__ import annotations

import os
from typing import Optional

from utils.logger import agent_log

# ── SendGrid SDK (optional) ──────────────────────────────────────────────────
try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import (
        Mail, Email, To, Content, Attachment,
        FileContent, FileName, FileType, Disposition, ContentId,
        TrackingSettings, ClickTracking, OpenTracking,
    )
    SENDGRID_AVAILABLE = True
except ImportError:
    SENDGRID_AVAILABLE = False
    agent_log("SENDGRID", "sendgrid package not installed — falling back to SMTP")


def send_email(
    to_email:           str,
    subject:            str,
    html_content:       str,
    sender_name:        str = "MarketOS",
    sender_email:       Optional[str] = None,
    unsubscribe_url:    str = "https://example.com/unsubscribe",
    campaign_id:        Optional[str] = None,
    hero_image_base64:  Optional[str] = None,
    hero_image_mime:    str = "image/jpeg",
) -> dict:
    """
    Send a transactional/marketing email.
    Tries SendGrid first, falls back to SMTP on failure or missing key.
    Returns: {"sent": bool, "provider": str, "error": str|None}
    """
    if os.getenv("PYTEST_CURRENT_TEST"):
        agent_log("SENDGRID", "Mocking send_email for tests")
        return {"sent": True, "provider": "Mock", "status_code": 200}
    
    api_key      = os.getenv("SENDGRID_API_KEY")
    from_email   = sender_email or os.getenv("SENDGRID_FROM_EMAIL") or os.getenv("SMTP_EMAIL")

    if SENDGRID_AVAILABLE and api_key and from_email:
        return _send_via_sendgrid(
            api_key, to_email, subject, html_content,
            sender_name, from_email, campaign_id, hero_image_base64, hero_image_mime,
        )

    # Fallback to SMTP
    agent_log("SENDGRID", "No SENDGRID_API_KEY — using SMTP fallback")
    return _send_via_smtp(to_email, subject, html_content, sender_name, unsubscribe_url, hero_image_base64)


def _send_via_sendgrid(
    api_key:           str,
    to_email:          str,
    subject:           str,
    html_content:      str,
    sender_name:       str,
    from_email:        str,
    campaign_id:       Optional[str],
    hero_image_base64: Optional[str],
    hero_image_mime:   str,
) -> dict:
    try:
        from sendgrid.helpers.mail import Header
        message = Mail(
            from_email=Email(from_email, sender_name),
            to_emails=To(to_email),
            subject=subject,
            html_content=Content("text/html", html_content),
        )

        # Custom headers for campaign tracking
        if campaign_id:
            message.add_header(Header("X-MarketOS-Campaign-ID", campaign_id))

        # Attach inline hero image if generated by Imagen
        if hero_image_base64:
            attachment = Attachment(
                file_content=FileContent(hero_image_base64),
                file_name=FileName("hero.jpg"),
                file_type=FileType(hero_image_mime),
                disposition=Disposition("inline"),
                content_id=ContentId("hero_image"),
            )
            message.add_attachment(attachment)

        # Enable tracking
        tracking = TrackingSettings()
        tracking.click_tracking  = ClickTracking(enable=True)
        tracking.open_tracking   = OpenTracking(enable=True)
        message.tracking_settings = tracking

        sg = SendGridAPIClient(api_key)
        response = sg.send(message)

        if response.status_code in (200, 202):
            agent_log("SENDGRID", f"✅ Email accepted — status {response.status_code} to {to_email}")
            return {"sent": True, "provider": "SendGrid", "status_code": response.status_code}
        else:
            agent_log("SENDGRID", f"❌ SendGrid rejected: {response.status_code} — {response.body}")
            return {"sent": False, "provider": "SendGrid", "error": f"Status {response.status_code}"}

    except Exception as e:
        agent_log("SENDGRID", f"❌ SendGrid exception: {e}")
        return {"sent": False, "provider": "SendGrid", "error": str(e)}


def _send_via_smtp(
    to_email:          str,
    subject:           str,
    html_content:      str,
    sender_name:       str,
    unsubscribe_url:   str,
    hero_image_base64: Optional[str],
) -> dict:
    """SMTP fallback (Gmail App Password)."""
    import smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    smtp_email    = os.getenv("SMTP_EMAIL")
    smtp_password = os.getenv("SMTP_PASSWORD")
    smtp_host     = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port     = int(os.getenv("SMTP_PORT", "587"))

    if not smtp_email or not smtp_password:
        return {"sent": False, "provider": "SMTP", "error": "No SMTP or SendGrid credentials configured"}

    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"]    = f"{sender_name} <{smtp_email}>"
    msg["To"]      = to_email

    alt = MIMEMultipart("alternative")
    msg.attach(alt)
    alt.attach(MIMEText(html_content, "html"))

    if hero_image_base64:
        import base64
        from email.mime.image import MIMEImage
        try:
            img_part = MIMEImage(base64.b64decode(hero_image_base64))
            img_part.add_header("Content-ID", "<hero_image>")
            img_part.add_header("Content-Disposition", "inline", filename="hero.jpg")
            msg.attach(img_part)
        except Exception as e:
            agent_log("SENDGRID", f"Image attach failed: {e}")

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_email, smtp_password)
            server.sendmail(smtp_email, to_email, msg.as_string())
        agent_log("SENDGRID", f"✅ SMTP sent to {to_email}")
        return {"sent": True, "provider": "SMTP"}
    except Exception as e:
        agent_log("SENDGRID", f"❌ SMTP failed: {e}")
        return {"sent": False, "provider": "SMTP", "error": str(e)}
