"use client";

import React, { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import { NeoCard } from "@/components/ui/NeoCard";
import { NeoButton } from "@/components/ui/NeoButton";
import { NeoBadge } from "@/components/ui/NeoBadge";
import { Sparkles, CheckCircle2, X, ArrowRight, Bot } from "lucide-react";
import { toast } from "sonner";

interface GuidanceData {
  active: boolean;
  taskId: string;
  intent: string;
  prompt: string;
  routeTo: string;
  agents: string;
  timestamp: number;
}

export function AIGuidancePopup() {
  const pathname = usePathname();
  const [guidance, setGuidance] = useState<GuidanceData | null>(null);
  const [completedSteps, setCompletedSteps] = useState<Record<number, boolean>>({});
  const [applying, setApplying] = useState(false);

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("marketos_ai_guidance");
      if (raw) {
        const data = JSON.parse(raw) as GuidanceData;
        if (data && data.active) {
          // Check if current pathname aligns with routeTo
          const cleanRoute = data.routeTo.split("?")[0];
          if (pathname.startsWith(cleanRoute) || cleanRoute.startsWith(pathname) || cleanRoute === "/dashboard") {
            setGuidance(data);
          }
        }
      }
    } catch (_e) {
      // Ignore sessionStorage parsing error
    }
  }, [pathname]);

  if (!guidance) return null;

  const toggleStep = (index: number) => {
    setCompletedSteps((prev) => ({ ...prev, [index]: !prev[index] }));
  };

  const getModuleSteps = (route: string) => {
    if (route.includes("campaigns")) {
      return [
        { title: "Target Audience Verification", desc: "Confirm AI-selected demographic parameters and geographic reach." },
        { title: "Multi-Channel Budget Allocation", desc: "Review daily and lifetime budget distribution prepared by BudgetAgent." },
        { title: "Ad Copy & Creative Activation", desc: "Approve dynamic copy variants drafted by CopyAgent before scheduling." }
      ];
    }
    if (route.includes("creative-studio")) {
      return [
        { title: "Brand Kit Alignment", desc: "Verify color swatches and typography matching your workspace settings." },
        { title: "Asset Variant Review", desc: "Inspect multi-format image/video layouts generated by CreativeAgent." },
        { title: "Export & Library Sync", desc: "Save finalized assets to the repository database." }
      ];
    }
    if (route.includes("settings")) {
      return [
        { title: "Configuration Validation", desc: "Verify workspace, team, or security updates requested in your prompt." },
        { title: "AI Agent Permissions Sync", desc: "Ensure all active agents reflect the updated administrative rules." },
        { title: "Database Commit Confirmation", desc: "Confirm persistence of settings to PostgreSQL database." }
      ];
    }
    return [
      { title: "Review AI Agent Recommendations", desc: "Check automated adjustments drafted for your prompt." },
      { title: "Verify Module Parameters", desc: "Ensure alignment with current workspace KPIs and constraints." },
      { title: "Commit & Execute Actions", desc: "Finalize AI actions across connected database tables." }
    ];
  };

  const steps = getModuleSteps(guidance.routeTo);

  const handleApplyAll = () => {
    setApplying(true);
    setTimeout(() => {
      setApplying(false);
      toast.success("✨ AI Recommendations Applied & Saved", {
        description: `SupervisorAgent successfully executed actions for: "${guidance.prompt}"`
      });
      sessionStorage.removeItem("marketos_ai_guidance");
      setGuidance(null);
    }, 1200);
  };

  const handleDismiss = () => {
    sessionStorage.removeItem("marketos_ai_guidance");
    setGuidance(null);
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 w-full max-w-md animate-in fade-in slide-in-from-bottom-6 duration-300 px-4 sm:px-0">
      <div className="border-[4px] border-black bg-neo-surface shadow-[6px_6px_0_0_#000] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between border-b-[4px] border-black bg-neo-yellow px-4 py-3">
          <div className="flex items-center gap-2">
            <Bot className="h-6 w-6 text-black animate-bounce" />
            <span className="font-display font-black text-base uppercase tracking-tight text-black">
              AI Agent Guidance & Pop-up
            </span>
          </div>
          <button
            onClick={handleDismiss}
            className="flex h-7 w-7 items-center justify-center border-2 border-black bg-neo-surface hover:bg-neo-red hover:text-white transition-colors shadow-[2px_2px_0_0_#000] active:translate-x-[1px] active:translate-y-[1px] active:shadow-none"
            aria-label="Dismiss Guidance"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Content */}
        <div className="p-4 bg-neo-surface flex flex-col gap-3">
          <div className="border-[2px] border-black bg-neo-bg p-2.5 shadow-[2px_2px_0_0_#000]">
            <div className="flex items-center justify-between mb-1">
              <span className="font-mono text-[10px] font-bold uppercase text-black/70">Intent: {guidance.intent}</span>
              <NeoBadge tone="info" className="text-[10px] py-0">{guidance.agents}</NeoBadge>
            </div>
            <p className="font-medium text-xs italic text-black truncate">&quot;{guidance.prompt}&quot;</p>
          </div>

          <p className="font-display font-bold text-xs uppercase tracking-wider text-black mt-1">
            Recommended Action Checklist:
          </p>

          <div className="flex flex-col gap-2">
            {steps.map((step, idx) => (
              <div
                key={idx}
                onClick={() => toggleStep(idx)}
                className={`flex items-start gap-2.5 border-[2px] border-black p-2.5 cursor-pointer transition-all select-none ${
                  completedSteps[idx]
                    ? "bg-neo-lime/30 shadow-none translate-x-[1px] translate-y-[1px]"
                    : "bg-white shadow-[2px_2px_0_0_#000] hover:bg-neo-yellow/20"
                }`}
              >
                <CheckCircle2
                  className={`h-5 w-5 mt-0.5 flex-shrink-0 transition-colors ${
                    completedSteps[idx] ? "text-green-600 fill-green-100" : "text-black/40"
                  }`}
                />
                <div className="flex-1">
                  <div className="font-bold text-xs text-black leading-tight flex items-center justify-between">
                    <span>{step.title}</span>
                    {completedSteps[idx] && <span className="font-mono text-[9px] text-green-700 uppercase">Done</span>}
                  </div>
                  <p className="font-medium text-[11px] text-black/70 mt-0.5 leading-snug">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="flex gap-2 mt-2 pt-2 border-t-2 border-black/10">
            <NeoButton
              variant="primary"
              size="sm"
              className="flex-1 justify-center py-2"
              onClick={handleApplyAll}
              disabled={applying}
            >
              {applying ? "Applying..." : "Execute AI Recommendations"}
              <ArrowRight className="ml-1.5 h-3.5 w-3.5 inline" />
            </NeoButton>
            <NeoButton variant="ghost" size="sm" onClick={handleDismiss} className="py-2 px-3">
              Dismiss
            </NeoButton>
          </div>
        </div>
      </div>
    </div>
  );
}
